### ISSUE TITLE
Questions about prompt

### ISSUE THREAD

**Issue by Yufang-Liu** [We-Math/We-Math#1]
Hi,

Thanks for the great works, impressive.

I did not find the prompt... Did I miss it ?
> Examples for generating responses from some LMMs are provided in the [evaluation](https://github.com/We-Math/We-Math/blob/main/evaluation). Our prompt specifies the format of answer generation to facilitate subsequent extraction of the answer using string matching. Please refer to the following template to prepare your result JSON files for subsequent evaluation.

**Comment by RQ-Lab** [comment]
Hi, thanks for your interest in We-Math.

The prompt of We-Math is included in Table 3 (on page 26 of the current version) and we will also update this on GitHub in the future.

Prompt:
"Now, we require you to solve a multiple-choice math question. Please briefly describe your thought process and provide the final answer(option).
Question: <Question>
Option: <Option>
Regarding the format, please answer following the template below, and be sure to include two <> symbols:
<Thought process>: <<your thought process>> <Answer>: <<your option>>"

**Comment by Runqi-QRQ** [comment]
Hi, thanks for your interest in We-Math.

The prompt of We-Math is included in Table 3 (on page 26 of the current version) and we will also update this on GitHub in the future.

```
Now, we require you to solve a multiple-choice math question. Please briefly describe your thought process and provide the final answer(option).
Question: <Question>
Option: <Option>
Regarding the format, please answer following the template below, and be sure to include two <> symbols:
<Thought process>: <<your thought process>> <Answer>: <<your option>>
