### ISSUE TITLE
Results of more advanced models.

### ISSUE THREAD

**Issue by lrlbbzl** [We-Math/We-Math#3]
This is a great piece of work. We are currently conducting related research, and I would like to know if the authors will update the test results for more advanced models such as Qwen2-VL and InternVL2-8B. We are considering comparing our model on WE-MATH. We will use the dataset properly and cite this work. Thanks.

**Comment by Runqi-QRQ** [comment]
Hi, thanks for your interest in We-Math.

We will release new updates on our website tomorrow. Below are some results for more advanced models, including Qwen2-VL and InternVL2-8B.

#### Accuracy scores of LMMs on the testmini subset of We-Math.

| **Model**             | **S1** | **S2** | **S3** | **Mem UCU** | **Mem AL** | **PF CPF** | **PF UPF** | **SF CSF** | **SF USF** | **TMF BTF** | **TMF CCF** | **PD Dir** | **PD Pos** | **PD RoM** | **PD CCP** |
|------------------------|--------|--------|--------|-------------|------------|------------|------------|------------|------------|-------------|-------------|------------|------------|------------|------------|
| **InternVL2-Llama3-76B** | 67.90  | 53.33  | 43.64  | 71.73       | 39.82      | 71.33      | 61.74      | 73.84      | 61.54      | 68.81       | 63.94       | 89.52      | 76.59      | 62.64      | 73.33      |
| **Qwen2-VL-72B**        | 68.15  | 53.06  | 50.91  | 92.36       | 45.09      | 70.20      | 63.76      | 72.93      | 58.47      | 61.34       | 71.01       | 75.48      | 72.67      | 66.76      | 70.00      |
| **LLaVA-OneVision-72B** | 63.95  | 45.83  | 35.76  | 73.81       | 35.79      | 69.62      | 62.15      | 72.84      | 57.35      | 46.28       | 65.05       | 61.67      | 65.92      | 40.93      | 56.67      |
| **InternVL2-8B**        | 59.42  | 43.61  | 35.15  | 71.43       | 20.53      | 61.95      | 55.54      | 67.10      | 57.29      | 54.03       | 60.51       | 58.57      | 63.62      | 44.51      | 50.00      |
| **Qwen2-VL-7B**         | 59.09  | 43.61  | 26.67  | 62.70       | 37.19      | 62.64      | 60.78      | 65.68      | 49.24      | 52.51       | 49.22       | 48.10      | 68.23      | 54.95      | 56.67      |
| **LLaVA-OneVision-7B**  | 57.45  | 43.06  | 39.39  | 59.03       | 36.49      | 66.66      | 55.36      | 64.39      | 61.09      | 48.63       | 46.90       | 55.00      | 49.53      | 25.55      | 43.33      |
| **InternVL2-4B**        | 50.45  | 32.50  | 24.85  | 43.95       | 30.53      | 55.68      | 47.72      | 58.04      | 56.92      | 38.63       | 41.39       | 34.52      | 53.44      | 52.20      | 46.67      |
| **InternVL2-2B**        | 38.93  | 31.11  | 22.42  | 28.67       | 35.79      | 44.22      | 38.24      | 37.47      | 34.48      | 36.47       | 35.35       | 48.33      | 51.67      | 29.40      | 23.33      |


#### The performance of different LMMs on four-dimensional metrics for reasoning evaluation.

| **Model**             | **Strict Avg** ($\uparrow$) | **Strict IK** ($\downarrow$) | **Strict IG** ($\downarrow$) | **Strict CM** ($\uparrow$) | **Strict RM** ($\downarrow$) | **Loose Avg** ($\uparrow$) | **Loose IK** ($\downarrow$) | **Loose IG** ($\downarrow$) | **Loose CM** ($\uparrow$) | **Loose RM** ($\downarrow$) |
|------------------------|----------------------------|-----------------------------|-----------------------------|----------------------------|-----------------------------|----------------------------|-----------------------------|-----------------------------|----------------------------|-----------------------------|
| **InternVL2-Llama3-76B** | 36.86%                     | 33.90% (178)                | 15.81% (83)                 | 28.95% (152)               | 42.42% (112)                | 56.29%                     | 33.90% (178)                | 15.81% (83)                 | 48.38% (254)               | 3.79% (10)                  |
| **Qwen2-VL-72B**        | 36.57%                     | 33.52% (176)                | 14.10% (74)                 | 29.52% (155)               | 43.64% (120)                | 56.76%                     | 33.52% (176)                | 14.10% (74)                 | 49.71% (261)               | 5.09% (14)                  |
| **LLaVA-OneVision-72B** | 28.67%                     | 41.14% (216)                | 16.19% (85)                 | 20.57% (108)               | 51.79% (116)                | 49.05%                     | 41.14% (216)                | 16.19% (85)                 | 40.95% (215)               | 4.02% (9)                   |
| **Qwen2-VL-7B**         | 25.62%                     | 47.05% (247)                | 14.67% (77)                 | 18.29% (96)                | 52.24% (105)                | 42.95%                     | 47.05% (247)                | 14.67% (77)                 | 35.62% (187)               | 6.97% (14)                  |
| **LLaVA-OneVision-7B**  | 23.14%                     | 44.95% (236)                | 13.14% (69)                 | 16.57% (87)                | 60.45% (133)                | 44.86%                     | 44.95% (236)                | 13.14% (69)                 | 38.29% (201)               | 8.64% (19)                  |
| **InternVL2-8B**        | 26.57%                     | 45.52% (239)                | 13.52% (71)                 | 19.81% (104)               | 51.63% (111)                | 44.86%                     | 45.52% (239)                | 13.52% (71)                 | 38.10% (200)               | 6.98% (15)                  |
| **InternVL2-4B**        | 17.43%                     | 59.81% (314)                | 10.10% (53)                 | 12.38% (65)                | 58.86% (93)                 | 31.52%                     | 59.81% (314)                | 10.10% (53)                 | 26.48% (139)               | 12.03% (19)                 |
| **InternVL2-2B**        | 9.14%                      | 64.00% (336)                | 7.62% (40)                  | 5.33% (28)                 | 81.21% (121)                | 25.14%                     | 64.00% (336)                | 7.62% (40)                  | 21.33% (112)               | 24.83% (37)                 |

**Comment by lrlbbzl** [comment]
Thanks for your prompt response!
